blank_issues_enabled: true
contact_links:
  - name: Support & Troubleshooting with the RISC Zero Community
    url: https://discord.com/invite/risczero
    about: |
      For general questions and problems you are facing with RISC Zero, please **search** our #🙋｜dev-questions-support-forum first for solutions. If you find no solution, feel free to ask any questions in our community! We encourage everyone to share their knowledge by answering questions for others!
