name: Feature Request
description: Submit your suggestions for new features or improvements to RISC Zero
labels: [ enhancement ]
body:
  - type: checkboxes
    id: existing
    attributes:
      label: Is there an existing issue?
      description: Please search to see if an issue already exists and leave a comment that you also experienced this issue or add your specifics that are related to an existing issue.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    id: stackexchange
    attributes:
      label: Experiencing problems? Have you tried our Discord first?
      description: Please search [our Discord server](https://discord.com/invite/risczero) to see if a post already exists, and ask if not. Please do not file support issues here.
      options:
        - label: This is not a support question.
          required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please provide context as to what led you to file this feature request.
      placeholder: |
        - What problem are you trying to solve?
        - How do you currently work around this?
        - Why is this feature important?
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Please describe what is needed.
      placeholder: |
        - What specific feature would you like to see?
        - How should it work from a user's perspective?
        - What would be the expected outcome?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: If possible, please describe what a solution could be.
      placeholder: |
        - Do you have ideas about how to implement this?
        - Are there similar features in other projects we could learn from?
    validations:
      required: false
  - type: dropdown
    id: help
    attributes:
      label: Are you willing to help with this request?
      multiple: true
      options:
        - Yes!
        - No.
        - Maybe... (I have elaborated on how above)
    validations:
      required: true
